<?php

namespace FeedsReaderBundle\Repository;

/**
 * FeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedRepository extends \Doctrine\ORM\EntityRepository
{
    const FEEDS_PER_PAGE = 5;
}
